spring.application.name=padel

spring.datasource.url=jdbc:mysql://localhost:3307/padel_db
spring.datasource.username=sa
spring.datasource.password=password

# TODO [FACULTATIF][PRODUCTION] En cas de déploiement réel, séparer les configurations dev/prod et externaliser les secrets.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

security.jwt.secret=${JWT_SECRET:maCleSecreteDeTestAuMoins32Caracteres}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.security.admin-default-password=${ADMIN_DEFAULT_PASSWORD:}

app.scheduling.enabled=true
app.scheduling.private-match-conversion-delay-ms=3600000
