spring.application.name=padel

# TODO [IMPORTANT][SECURITE] Externaliser les identifiants de base de donnees via variables d'environnement.
spring.datasource.url=jdbc:mysql://localhost:3307/padel_db
spring.datasource.username=sa
spring.datasource.password=password

# TODO [IMPORTANT][ARCHITECTURE] Utiliser des profils dev/test/prod pour adapter ddl-auto, show-sql et la base de tests.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
